// M0 — independently reproduce next/font's CLS-safe adjusted fallback for Fraunces,
// using @capsizecss/metrics + next/font's documented formula. Writes the generated
// candidate font CSS the /preview route and the dev panel consume, plus a JSON artifact
// the comparison step checks against next/font's real emitted output.
//
// next/font formula (packages/next/src/server/font-utils.ts):
//   sizeAdjust       = (xWidthAvg/unitsPerEm) / (fallback.xWidthAvg/fallback.unitsPerEm)
//   ascent-override  = |ascent  / (unitsPerEm * sizeAdjust)| * 100
//   descent-override = |descent / (unitsPerEm * sizeAdjust)| * 100
//   line-gap-override= |lineGap / (unitsPerEm * sizeAdjust)| * 100
//   serif category -> Times New Roman fallback; else Arial.

import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import fraunces from "@capsizecss/metrics/fraunces";
import timesNewRoman from "@capsizecss/metrics/timesNewRoman";

const APP = fileURLToPath(new URL("../../examples/sample-next-site/", import.meta.url));
const OUT = fileURLToPath(new URL("./out/", import.meta.url));
mkdirSync(OUT, { recursive: true });

const main = fraunces;
const fallback = main.category === "serif" ? timesNewRoman : timesNewRoman; // Fraunces is serif
const fallbackName = "Times New Roman";

const sizeAdjust =
  main.xWidthAvg / main.unitsPerEm / (fallback.xWidthAvg / fallback.unitsPerEm);
const pct = (n) => `${(Math.abs(n) * 100).toFixed(2)}%`;

const overrides = {
  sizeAdjust: pct(sizeAdjust),
  ascentOverride: pct(main.ascent / (main.unitsPerEm * sizeAdjust)),
  descentOverride: pct(main.descent / (main.unitsPerEm * sizeAdjust)),
  lineGapOverride: pct(main.lineGap / (main.unitsPerEm * sizeAdjust)),
};

const css = `
@font-face {
  font-family: 'FL Fraunces';
  font-style: normal;
  font-weight: 100 900;
  font-display: swap;
  src: url('/fontlab/fraunces.woff2') format('woff2');
}
@font-face {
  font-family: 'FL Fraunces Fallback';
  src: local('Times New Roman');
  size-adjust: ${overrides.sizeAdjust};
  ascent-override: ${overrides.ascentOverride};
  descent-override: ${overrides.descentOverride};
  line-gap-override: ${overrides.lineGapOverride};
}
`;

const ts = `// AUTO-GENERATED by spike/m0/gen-fonts.mjs — do not edit by hand.
export const CANDIDATE_FAMILY = "'FL Fraunces', 'FL Fraunces Fallback', serif";

export const candidateFontFaceCss = ${JSON.stringify(css)};

export const computedOverrides = ${JSON.stringify({ font: "Fraunces", fallback: fallbackName, ...overrides }, null, 2)};
`;

writeFileSync(APP + "app/_fontlab/generated-fonts.ts", ts);
writeFileSync(OUT + "computed.json", JSON.stringify({ font: "Fraunces", fallback: fallbackName, ...overrides }, null, 2));

console.log("metrics(Fraunces):", JSON.stringify(main));
console.log("metrics(Times New Roman):", JSON.stringify(fallback));
console.log("computed overrides:", overrides);
console.log("wrote app/_fontlab/generated-fonts.ts and out/computed.json");
