// generateCatalog — the reusable parity-bundle builder (M5 extraction of gen-catalog's core).
//
// Given a project dir and a set of directions (curated OR agent-composed — both validated
// against the catalog), it self-hosts each font's Google variable woff2, computes next/font's
// exact adjusted fallback (M0-proven parity), and writes the generated module the dev panel
// imports plus the woff2 into the project's public/fontlab/. Pure of policy — WHICH directions
// to build is the caller's choice (the curator default, or the agent's own composition).

import { execFileSync } from "node:child_process";
import { writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { get as catalogGet } from "./catalog.mjs";
import { fontsForDirections } from "./curator.mjs";

const UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";
const slug = (family) => family.toLowerCase().replace(/[^a-z0-9]+/g, "-");
const pct = (n) => `${(Math.abs(n) * 100).toFixed(2)}%`;
const generic = (cat) => (cat === "serif" ? "serif" : cat === "monospace" ? "monospace" : "sans-serif");

const metricsFor = async (s) => (await import("@capsizecss/metrics/" + s)).default;

// next/font's adjusted-fallback descriptors for `main` measured against `fallback`.
function overrides(main, fallback) {
  const sizeAdjust = main.xWidthAvg / main.unitsPerEm / (fallback.xWidthAvg / fallback.unitsPerEm);
  return {
    sizeAdjust: pct(sizeAdjust),
    ascent: pct(main.ascent / (main.unitsPerEm * sizeAdjust)),
    descent: pct(main.descent / (main.unitsPerEm * sizeAdjust)),
    lineGap: pct(main.lineGap / (main.unitsPerEm * sizeAdjust)),
  };
}

/**
 * Build the parity catalog for `directions` into `projectDir`.
 * @param projectDir  absolute path to the Next.js project (panel lives at app/_fontlab/)
 * @param directions  the directions to render (each role family MUST be a catalog member)
 * @param meta        { target, replaces } baked into the generated module (from the analyzer)
 * @param opts        { log?: (msg)=>void, fetch?: boolean }  fetch:false skips network (test)
 * @returns { fonts, directions, outPath }
 */
export async function generateCatalog(projectDir, directions, meta = {}, opts = {}) {
  const log = opts.log || (() => {});
  const APP = projectDir.replace(/\/?$/, "/");
  const PUBLIC = APP + "public/fontlab/";
  mkdirSync(PUBLIC, { recursive: true });

  const arial = await metricsFor("arial");
  const timesNewRoman = await metricsFor("timesNewRoman");

  const faceCss = [];
  const stacks = {};
  const families = fontsForDirections(directions);

  for (const family of families) {
    const spec = catalogGet(family); // throws if not a verified catalog member

    if (opts.fetch !== false) {
      const css = execFileSync("curl", ["-sSL", "-A", UA, `https://fonts.googleapis.com/css2?family=${spec.css2}&display=swap`], { encoding: "utf8" });
      const m = css.match(/\/\* latin \*\/\s*@font-face\s*\{[^}]*?url\((https:[^)]+\.woff2)\)/);
      if (!m) throw new Error(`Could not find latin woff2 for "${family}"`);
      execFileSync("curl", ["-sSL", "-A", UA, "-o", PUBLIC + slug(family) + ".woff2", m[1]]);
    }

    const main = await metricsFor(spec.capsize);
    const isSerif = main.category === "serif";
    const fb = isSerif ? timesNewRoman : arial;
    const fbName = isSerif ? "Times New Roman" : "Arial";
    const o = overrides(main, fb);

    faceCss.push(
      `@font-face{font-family:'FL ${family}';font-style:normal;font-weight:100 900;font-display:swap;src:url('/fontlab/${slug(family)}.woff2') format('woff2');}`,
      `@font-face{font-family:'FL ${family} Fallback';src:local('${fbName}');size-adjust:${o.sizeAdjust};ascent-override:${o.ascent};descent-override:${o.descent};line-gap-override:${o.lineGap};}`,
    );
    stacks[family] = `'FL ${family}', 'FL ${family} Fallback', ${generic(main.category)}`;
    log(`  ${family.padEnd(20)} -> ${slug(family)}.woff2  (fallback ${fbName}, size-adjust ${o.sizeAdjust})`);
  }

  const outDirections = directions.map((d) => ({
    id: d.id,
    name: d.name,
    vibe: d.vibe,
    rationale: d.rationale,
    roles: Object.fromEntries(
      Object.entries(d.roles).map(([role, r]) => [role, { family: r.family, source: "google", weights: r.weights, stack: stacks[r.family] }]),
    ),
  }));

  const ts = `// AUTO-GENERATED by cli/gen-catalog.mjs — do not edit by hand.
import type { CSSProperties } from "react";

export const catalogFontFaceCss = ${JSON.stringify("\n" + faceCss.join("\n") + "\n")};

export const target = ${JSON.stringify(meta.target ?? null, null, 2)} as const;
export const replaces = ${JSON.stringify(meta.replaces ?? null, null, 2)} as const;

// Per-role preview swap target (M5/M6): which leaf var to override and on which element. The
// portable panel reads this so the live swap is honest on any site. null = unswappable role.
export const wiring = ${JSON.stringify(meta.wiring ?? null, null, 2)} as const;

export type Role = "display" | "body" | "mono";
export type RoleFont = { family: string; source: string; weights: number[]; stack: string };
export type Direction = {
  id: string;
  name: string;
  vibe: string;
  rationale: string;
  roles: Record<Role, RoleFont>;
};

export const directions: Direction[] = ${JSON.stringify(outDirections, null, 2)};

// CSS-variable overrides a direction applies on :root (the swap mechanism, M0-proven).
export function directionVars(d: Direction): CSSProperties {
  return {
    "--fl-display": d.roles.display.stack,
    "--fl-sans": d.roles.body.stack,
    "--fl-mono": d.roles.mono.stack,
  } as CSSProperties;
}
`;

  const outPath = path.join(APP, "app/_fontlab/catalog.generated.ts");
  mkdirSync(path.dirname(outPath), { recursive: true });
  writeFileSync(outPath, ts);
  return { fonts: families, directions: outDirections, outPath };
}
