// M1 — build the "parity catalog" the dev panel previews from: for every font in the two
// directions, self-host the Google woff2 and compute next/font's exact adjusted fallback
// (M0 proved this renders identically to ship). Writes the generated module the fixture's
// panel imports, plus the woff2 files into the fixture's public/fontlab/.
//
// Uses curl (which honors the sandbox HTTPS proxy) to fetch from Google.

import { execFileSync } from "node:child_process";
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { fonts, directions } from "./directions.mjs";
import { analyzeProject, toTarget } from "./analyzer.mjs";

const arg = (flag, def) => {
  const i = process.argv.indexOf(flag);
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : def;
};
const APP = (arg("--project", fileURLToPath(new URL("../examples/sample-next-site/", import.meta.url))) + "/").replace(/\/+$/, "/");
const PUBLIC = APP + "public/fontlab/";
mkdirSync(PUBLIC, { recursive: true });

// M3: the panel's "current" and before/after toggle are no longer hand-written — the
// analyzer reads the real project. target -> codegen branch; replaces -> the live current
// state the preview compares each direction against.
const analysis = analyzeProject(APP);
const target = toTarget(analysis);
const replaces = analysis.replaces;
console.log(
  `  analyzed ${analysis.router}/${target.framework} · tailwind v${target.tailwindVersion} · ${target.fontWiring}` +
    ` · current: ${replaces.display ?? "—"} / ${replaces.body ?? "—"} / ${replaces.mono ?? "—"}`,
);

const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";
const slug = (family) => family.toLowerCase().replace(/[^a-z0-9]+/g, "-");
const pct = (n) => `${(Math.abs(n) * 100).toFixed(2)}%`;
const generic = (cat) => (cat === "serif" ? "serif" : cat === "monospace" ? "monospace" : "sans-serif");

async function metricsFor(capsizeSlug) {
  return (await import("@capsizecss/metrics/" + capsizeSlug)).default;
}

// Compute next/font's adjusted-fallback descriptors for `main` against its fallback.
function overrides(main, fallback) {
  const sizeAdjust = main.xWidthAvg / main.unitsPerEm / (fallback.xWidthAvg / fallback.unitsPerEm);
  return {
    sizeAdjust: pct(sizeAdjust),
    ascent: pct(main.ascent / (main.unitsPerEm * sizeAdjust)),
    descent: pct(main.descent / (main.unitsPerEm * sizeAdjust)),
    lineGap: pct(main.lineGap / (main.unitsPerEm * sizeAdjust)),
  };
}

const arial = await metricsFor("arial");
const timesNewRoman = await metricsFor("timesNewRoman");

const faceCss = [];
const stacks = {}; // family -> css family stack string

const families = [...new Set(directions.flatMap((d) => Object.values(d.roles).map((r) => r.family)))];

for (const family of families) {
  const spec = fonts[family];
  if (!spec) throw new Error(`No fonts[] entry for "${family}"`);

  // 1) fetch the latin woff2 URL from Google css2 and self-host it.
  const css = execFileSync("curl", ["-sSL", "-A", UA, `https://fonts.googleapis.com/css2?family=${spec.css2}&display=swap`], { encoding: "utf8" });
  const m = css.match(/\/\* latin \*\/\s*@font-face\s*\{[^}]*?url\((https:[^)]+\.woff2)\)/);
  if (!m) throw new Error(`Could not find latin woff2 for "${family}"`);
  const dest = PUBLIC + slug(family) + ".woff2";
  execFileSync("curl", ["-sSL", "-A", UA, "-o", dest, m[1]]);

  // 2) compute next/font-identical adjusted fallback from capsize.
  const main = await metricsFor(spec.capsize);
  const isSerif = main.category === "serif";
  const fb = isSerif ? timesNewRoman : arial;
  const fbName = isSerif ? "Times New Roman" : "Arial";
  const o = overrides(main, fb);

  faceCss.push(
    `@font-face{font-family:'FL ${family}';font-style:normal;font-weight:100 900;font-display:swap;src:url('/fontlab/${slug(family)}.woff2') format('woff2');}`,
    `@font-face{font-family:'FL ${family} Fallback';src:local('${fbName}');size-adjust:${o.sizeAdjust};ascent-override:${o.ascent};descent-override:${o.descent};line-gap-override:${o.lineGap};}`,
  );
  stacks[family] = `'FL ${family}', 'FL ${family} Fallback', ${generic(main.category)}`;
  console.log(`  ${family.padEnd(20)} -> ${slug(family)}.woff2  (fallback ${fbName}, size-adjust ${o.sizeAdjust})`);
}

// Assemble the generated directions with both data (for selection.json) and css stacks.
const outDirections = directions.map((d) => ({
  id: d.id,
  name: d.name,
  vibe: d.vibe,
  rationale: d.rationale,
  roles: Object.fromEntries(
    Object.entries(d.roles).map(([role, r]) => [
      role,
      { family: r.family, source: "google", weights: r.weights, stack: stacks[r.family] },
    ]),
  ),
}));

const ts = `// AUTO-GENERATED by cli/gen-catalog.mjs — do not edit by hand.
import type { CSSProperties } from "react";

export const catalogFontFaceCss = ${JSON.stringify("\n" + faceCss.join("\n") + "\n")};

export const target = ${JSON.stringify(target, null, 2)} as const;
export const replaces = ${JSON.stringify(replaces, null, 2)} as const;

export type Role = "display" | "body" | "mono";
export type RoleFont = { family: string; source: string; weights: number[]; stack: string };
export type Direction = {
  id: string;
  name: string;
  vibe: string;
  rationale: string;
  roles: Record<Role, RoleFont>;
};

export const directions: Direction[] = ${JSON.stringify(outDirections, null, 2)};

// CSS-variable overrides a direction applies on :root (the swap mechanism, M0-proven).
export function directionVars(d: Direction): CSSProperties {
  return {
    "--fl-display": d.roles.display.stack,
    "--fl-sans": d.roles.body.stack,
    "--fl-mono": d.roles.mono.stack,
  } as CSSProperties;
}
`;

writeFileSync(APP + "app/_fontlab/catalog.generated.ts", ts);
console.log(`\nwrote app/_fontlab/catalog.generated.ts (${families.length} fonts, ${outDirections.length} directions)`);
