// AUTO-GENERATED by cli/gen-catalog.mjs — do not edit by hand.
import type { CSSProperties } from "react";

export const catalogFontFaceCss = "\n@font-face{font-family:'FL Fraunces';font-style:normal;font-weight:100 900;font-display:swap;src:url('/fontlab/fraunces.woff2') format('woff2');}\n@font-face{font-family:'FL Fraunces Fallback';src:local('Times New Roman');size-adjust:115.45%;ascent-override:84.71%;descent-override:22.09%;line-gap-override:0.00%;}\n@font-face{font-family:'FL Libre Franklin';font-style:normal;font-weight:100 900;font-display:swap;src:url('/fontlab/libre-franklin.woff2') format('woff2');}\n@font-face{font-family:'FL Libre Franklin Fallback';src:local('Arial');size-adjust:104.31%;ascent-override:92.61%;descent-override:23.58%;line-gap-override:0.00%;}\n@font-face{font-family:'FL JetBrains Mono';font-style:normal;font-weight:100 900;font-display:swap;src:url('/fontlab/jetbrains-mono.woff2') format('woff2');}\n@font-face{font-family:'FL JetBrains Mono Fallback';src:local('Arial');size-adjust:134.59%;ascent-override:75.79%;descent-override:22.29%;line-gap-override:0.00%;}\n@font-face{font-family:'FL Bricolage Grotesque';font-style:normal;font-weight:100 900;font-display:swap;src:url('/fontlab/bricolage-grotesque.woff2') format('woff2');}\n@font-face{font-family:'FL Bricolage Grotesque Fallback';src:local('Arial');size-adjust:105.43%;ascent-override:88.21%;descent-override:25.61%;line-gap-override:0.00%;}\n@font-face{font-family:'FL Figtree';font-style:normal;font-weight:100 900;font-display:swap;src:url('/fontlab/figtree.woff2') format('woff2');}\n@font-face{font-family:'FL Figtree Fallback';src:local('Arial');size-adjust:100.72%;ascent-override:94.32%;descent-override:24.82%;line-gap-override:0.00%;}\n";

export const target = {
  "framework": "next",
  "router": "app",
  "styling": "tailwind",
  "tailwindVersion": 4,
  "fontWiring": "css-variables"
} as const;
export const replaces = {
  "display": "Inter",
  "body": "Inter",
  "mono": "JetBrains Mono"
} as const;

export type Role = "display" | "body" | "mono";
export type RoleFont = { family: string; source: string; weights: number[]; stack: string };
export type Direction = {
  id: string;
  name: string;
  vibe: string;
  rationale: string;
  roles: Record<Role, RoleFont>;
};

export const directions: Direction[] = [
  {
    "id": "editorial-serif",
    "name": "Editorial",
    "vibe": "editorial",
    "rationale": "Warm high-contrast serif headlines over a clean grotesque body.",
    "roles": {
      "display": {
        "family": "Fraunces",
        "source": "google",
        "weights": [
          400,
          700
        ],
        "stack": "'FL Fraunces', 'FL Fraunces Fallback', serif"
      },
      "body": {
        "family": "Libre Franklin",
        "source": "google",
        "weights": [
          400,
          600
        ],
        "stack": "'FL Libre Franklin', 'FL Libre Franklin Fallback', sans-serif"
      },
      "mono": {
        "family": "JetBrains Mono",
        "source": "google",
        "weights": [
          400,
          700
        ],
        "stack": "'FL JetBrains Mono', 'FL JetBrains Mono Fallback', monospace"
      }
    }
  },
  {
    "id": "modern-grotesque",
    "name": "Modern Grotesque",
    "vibe": "technical",
    "rationale": "A characterful display grotesque over a quiet geometric body.",
    "roles": {
      "display": {
        "family": "Bricolage Grotesque",
        "source": "google",
        "weights": [
          400,
          700
        ],
        "stack": "'FL Bricolage Grotesque', 'FL Bricolage Grotesque Fallback', sans-serif"
      },
      "body": {
        "family": "Figtree",
        "source": "google",
        "weights": [
          400,
          600
        ],
        "stack": "'FL Figtree', 'FL Figtree Fallback', sans-serif"
      },
      "mono": {
        "family": "JetBrains Mono",
        "source": "google",
        "weights": [
          400,
          700
        ],
        "stack": "'FL JetBrains Mono', 'FL JetBrains Mono Fallback', monospace"
      }
    }
  }
];

// CSS-variable overrides a direction applies on :root (the swap mechanism, M0-proven).
export function directionVars(d: Direction): CSSProperties {
  return {
    "--fl-display": d.roles.display.stack,
    "--fl-sans": d.roles.body.stack,
    "--fl-mono": d.roles.mono.stack,
  } as CSSProperties;
}
