// AUTO-GENERATED by spike/m0/gen-fonts.mjs — do not edit by hand.
export const CANDIDATE_FAMILY = "'FL Fraunces', 'FL Fraunces Fallback', serif";

export const candidateFontFaceCss = "\n@font-face {\n  font-family: 'FL Fraunces';\n  font-style: normal;\n  font-weight: 100 900;\n  font-display: swap;\n  src: url('/fontlab/fraunces.woff2') format('woff2');\n}\n@font-face {\n  font-family: 'FL Fraunces Fallback';\n  src: local('Times New Roman');\n  size-adjust: 115.45%;\n  ascent-override: 84.71%;\n  descent-override: 22.09%;\n  line-gap-override: 0.00%;\n}\n";

export const computedOverrides = {
  "font": "Fraunces",
  "fallback": "Times New Roman",
  "sizeAdjust": "115.45%",
  "ascentOverride": "84.71%",
  "descentOverride": "22.09%",
  "lineGapOverride": "0.00%"
};
